package main

import (
	"strings"
	"unicode/utf8"

	"github.com/google/uuid"
)

// vcard.go is a small vCard 3.0 (RFC 2426) reader/writer. A contact carries
// several emails, phones, etc. (vCard TEL/EMAIL/ADR are lists). The full raw
// card is kept on the Contact so fields we do not model survive a round-trip
// through CardDAV; when the card is rebuilt for a web edit, every line except
// the regenerated fields is carried over untouched.

// VCardField is one entry of a repeating vCard property (EMAIL, TEL, ...).
// Type holds the TYPE= parameter values (HOME, WORK, CELL, INTERNET, ...) and
// Header keeps the original property line (group + params) so re-serialising
// stays faithful even for unknown parameters.
type VCardField struct {
	Type   []string `json:"type,omitempty"`
	Value  string   `json:"value"`
	Header string   `json:"header,omitempty"`
}

// TypeLabel is used by page templates, e.g. "WORK/CELL".
func (f VCardField) TypeLabel() string { return strings.Join(f.Type, "/") }

// displayName derives a formatted name for a Contact, preferring structured
// name parts over the stored FN and falling back to company, then the first
// email.
func (c Contact) displayName() string {
	first := strings.TrimSpace(c.FirstName)
	last := strings.TrimSpace(c.LastName)
	if first != "" || last != "" {
		return strings.TrimSpace(first + " " + last)
	}
	if company := strings.TrimSpace(c.Company); company != "" {
		return company
	}
	if name := strings.TrimSpace(c.Name); name != "" {
		return name
	}
	if len(c.Emails) > 0 {
		return c.Emails[0].Value
	}
	return c.Email
}

// baseVCardFields are regenerated by buildVCard; every other line in the stored
// card is preserved verbatim. UID is regenerated too: a client-supplied one is
// kept, otherwise the contact id gives a stable value.
var baseVCardFields = map[string]bool{
	"FN": true, "N": true, "ORG": true, "TITLE": true, "TEL": true, "EMAIL": true,
	"UID": true,
}

// unfoldVCard splits a vCard into logical lines, joining folded continuations
// (a continuation starts with a space or tab).
func unfoldVCard(v string) []string {
	var lines []string
	var buf string
	for _, raw := range strings.Split(v, "\n") {
		line := strings.TrimSuffix(raw, "\r")
		if len(line) > 0 && (line[0] == ' ' || line[0] == '\t') && buf != "" {
			if len(line) > 1 {
				buf += line[1:]
			}
			continue
		}
		if buf != "" {
			lines = append(lines, buf)
		}
		buf = line
	}
	if buf != "" {
		lines = append(lines, buf)
	}
	return lines
}

func splitVCardLine(line string) (header, value string) {
	if i := strings.IndexByte(line, ':'); i >= 0 {
		return line[:i], line[i+1:]
	}
	return line, ""
}

func escapeVCardValue(v string) string {
	v = strings.ReplaceAll(v, `\`, `\\`)
	v = strings.ReplaceAll(v, "\n", `\n`)
	v = strings.ReplaceAll(v, ",", `\,`)
	v = strings.ReplaceAll(v, ";", `\;`)
	return v
}

func unescapeVCardValue(v string) string {
	v = strings.ReplaceAll(v, `\n`, "\n")
	v = strings.ReplaceAll(v, `\N`, "\n")
	v = strings.ReplaceAll(v, `\,`, ",")
	v = strings.ReplaceAll(v, `\;`, ";")
	v = strings.ReplaceAll(v, `\\`, `\`)
	return v
}

// splitEscaped splits on sep, ignoring separators escaped with a backslash
// (RFC 2426 uses \n, \, and \; inside escaped values).
func splitEscaped(s string, sep byte) []string {
	var parts []string
	var cur strings.Builder
	escaped := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case escaped:
			escaped = false
		case c == '\\':
			escaped = true
		case c == sep:
			parts = append(parts, cur.String())
			cur.Reset()
			continue
		}
		cur.WriteByte(c)
	}
	parts = append(parts, cur.String())
	return parts
}

// foldVCardLine folds a line at 75 octets (RFC 6868 / RFC 2426), staying on
// UTF-8 rune boundaries.
func foldVCardLine(s string) string {
	if len(s) <= 75 {
		return s
	}
	var out []string
	for len(s) > 75 {
		cut := 75
		for cut > 0 && !utf8.RuneStart(s[cut]) {
			cut--
		}
		if cut == 0 {
			cut = 75
		}
		out = append(out, s[:cut])
		s = s[cut:]
	}
	out = append(out, s)
	return strings.Join(out, "\n ")
}

// parseVCardFields reads the structured fields we model out of a vCard and
// keeps the raw card in VCard so nothing is lost. Repeating properties (EMAIL,
// TEL) are collected in order, with their TYPE parameters preserved.
func parseVCardFields(v string) Contact {
	var ct Contact
	ct.VCard = strings.TrimSpace(v)

	for _, line := range unfoldVCard(v) {
		hdr, val := splitVCardLine(line)
		name := hdr
		if i := strings.IndexByte(hdr, ';'); i >= 0 {
			name = hdr[:i]
		}
		switch strings.ToUpper(name) {
		case "EMAIL":
			ct.Emails = append(ct.Emails, vCardFieldFromLine(hdr, val))
		case "UID":
			ct.UID = strings.TrimSpace(unescapeVCardValue(val))
		case "FN":
			ct.Name = strings.TrimSpace(unescapeVCardValue(val))
		case "N":
			parts := splitEscaped(val, ';')
			if len(parts) > 0 {
				ct.LastName = strings.TrimSpace(unescapeVCardValue(parts[0]))
			}
			if len(parts) > 1 {
				ct.FirstName = strings.TrimSpace(unescapeVCardValue(parts[1]))
			}
		case "ORG":
			if parts := splitEscaped(val, ';'); len(parts) > 0 {
				ct.Company = strings.TrimSpace(unescapeVCardValue(parts[0]))
			}
		case "TITLE":
			ct.Title = strings.TrimSpace(unescapeVCardValue(val))
		case "TEL":
			ct.Phones = append(ct.Phones, vCardFieldFromLine(hdr, val))
		}
	}
	// The first email stays the contact's primary email (own column + identity
	// de-duplication); it also feeds DisplayName when the card has no name.
	if len(ct.Emails) > 0 {
		ct.Email = ct.Emails[0].Value
	}
	if ct.Name == "" {
		ct.Name = strings.TrimSpace(strings.Join([]string{ct.FirstName, ct.LastName}, " "))
	}
	if ct.Name == "" {
		ct.Name = ct.Email
	}
	return ct
}

// vCardFieldFromLine builds a VCardField from a parsed property line even when
// the value contains escaped separators.
func vCardFieldFromLine(hdr, val string) VCardField {
	f := VCardField{Header: hdr, Value: strings.TrimSpace(unescapeVCardValue(val))}
	if i := strings.IndexByte(hdr, ';'); i >= 0 {
		for _, param := range strings.Split(hdr[i+1:], ";") {
			name, value, ok := strings.Cut(strings.TrimSpace(param), "=")
			if !ok {
				continue
			}
			if strings.EqualFold(name, "TYPE") {
				for _, t := range strings.Split(value, ",") {
					if t = strings.TrimSpace(t); t != "" {
						f.Type = append(f.Type, strings.ToUpper(t))
					}
				}
			}
		}
	}
	return f
}

// fieldLine serialises one TEL/EMAIL field back to a vCard line, preferring the
// original property header (params preserved) and defaulting sensibly for
// fields created through the web UI.
func fieldLine(kind string, f VCardField) string {
	hdr := f.Header
	if hdr == "" {
		switch kind {
		case "EMAIL":
			hdr = "EMAIL;TYPE=INTERNET"
		case "TEL":
			hdr = "TEL;TYPE=CELL,VOICE"
		}
	}
	if f.Value != "" {
		return hdr + ":" + escapeVCardValue(f.Value)
	}
	return ""
}

// uidFor picks the vCard UID for a rebuilt card: the parsed one wins, then the
// previous card's, and a web-created contact falls back to its immutable id so
// every card carries a UID (clients ignore cards that lack one).
func uidFor(ct Contact, prev string) string {
	if uid := strings.TrimSpace(ct.UID); uid != "" {
		return uid
	}
	for _, line := range unfoldVCard(prev) {
		hdr, val := splitVCardLine(line)
		name := hdr
		if i := strings.IndexByte(hdr, ';'); i >= 0 {
			name = hdr[:i]
		}
		if strings.EqualFold(name, "UID") {
			if uid := strings.TrimSpace(unescapeVCardValue(val)); uid != "" {
				return uid
			}
		}
	}
	if ct.ID != uuid.Nil {
		return ct.ID.String()
	}
	return ""
}

// buildVCard serializes a Contact, preserving every non-base line from the
// previously stored card so CardDAV-only fields (ADR, NOTE, BDAY, ...) survive
// edits made in the web UI.
func buildVCard(ct Contact, prev string) string {
	var extras []string
	for _, line := range unfoldVCard(prev) {
		hdr, _ := splitVCardLine(line)
		name := hdr
		if i := strings.IndexByte(hdr, ';'); i >= 0 {
			name = hdr[:i]
		}
		if !baseVCardFields[strings.ToUpper(name)] {
			extras = append(extras, line)
		}
	}

	lines := []string{"BEGIN:VCARD", "VERSION:3.0"}
	if fn := ct.displayName(); fn != "" {
		lines = append(lines, "FN:"+escapeVCardValue(fn))
	}
	if ct.FirstName != "" || ct.LastName != "" {
		lines = append(lines, "N:"+escapeVCardValue(ct.LastName)+";"+escapeVCardValue(ct.FirstName)+";;;")
	} else if ct.Name != "" {
		lines = append(lines, "N:"+escapeVCardValue(ct.Name)+";;;;")
	}
	if uid := uidFor(ct, prev); uid != "" {
		lines = append(lines, "UID:"+escapeVCardValue(uid))
	}
	if ct.Company != "" {
		lines = append(lines, "ORG:"+escapeVCardValue(ct.Company))
	}
	if ct.Title != "" {
		lines = append(lines, "TITLE:"+escapeVCardValue(ct.Title))
	}
	for _, f := range ct.Phones {
		if line := fieldLine("TEL", f); line != "" {
			lines = append(lines, line)
		}
	}
	for _, f := range ct.Emails {
		if line := fieldLine("EMAIL", f); line != "" {
			lines = append(lines, line)
		}
	}
	lines = append(lines, extras...)
	lines = append(lines, "END:VCARD")

	var out []string
	for _, l := range lines {
		out = append(out, foldVCardLine(l))
	}
	return strings.Join(out, "\n")
}
