package vcard

import (
	"strings"
	"unicode/utf8"

	"github.com/bklimczak/workspace/internal/contacts"
	"github.com/google/uuid"
)

// vCard 3.0 (RFC 2426) reader/writer. A contact carries several emails,
// phones, etc. (vCard TEL/EMAIL/ADR are lists). The full raw card is kept on
// the Contact so fields we do not model survive a round-trip through CardDAV;
// when the card is rebuilt for a web edit, every line except the regenerated
// fields is carried over untouched.

// baseFields are regenerated by Encode; every other line in the stored card
// is preserved verbatim. UID is regenerated too: a client-supplied one is
// kept, otherwise the contact id gives a stable value.
var baseFields = map[string]bool{
	"FN": true, "N": true, "ORG": true, "TITLE": true, "TEL": true, "EMAIL": true,
	"UID": true,
}

// Parse reads the structured fields we model out of a vCard and keeps the raw
// card in VCard so nothing is lost. Repeating properties (EMAIL, TEL) are
// collected in order, with their TYPE parameters preserved.
func Parse(raw string) contacts.Contact {
	var ct contacts.Contact
	ct.VCard = strings.TrimSpace(raw)

	for _, line := range unfold(raw) {
		hdr, val := splitLine(line)
		name := hdr
		if i := strings.IndexByte(hdr, ';'); i >= 0 {
			name = hdr[:i]
		}
		switch strings.ToUpper(name) {
		case "EMAIL":
			ct.Emails = append(ct.Emails, fieldFromLine(hdr, val))
		case "UID":
			ct.UID = strings.TrimSpace(unescapeValue(val))
		case "FN":
			ct.Name = strings.TrimSpace(unescapeValue(val))
		case "N":
			parts := splitEscaped(val, ';')
			if len(parts) > 0 {
				ct.LastName = strings.TrimSpace(unescapeValue(parts[0]))
			}
			if len(parts) > 1 {
				ct.FirstName = strings.TrimSpace(unescapeValue(parts[1]))
			}
		case "ORG":
			if parts := splitEscaped(val, ';'); len(parts) > 0 {
				ct.Company = strings.TrimSpace(unescapeValue(parts[0]))
			}
		case "TITLE":
			ct.Title = strings.TrimSpace(unescapeValue(val))
		case "TEL":
			ct.Phones = append(ct.Phones, fieldFromLine(hdr, val))
		}
	}
	// The first email stays the contact's primary email (own column + identity
	// de-duplication); it also feeds DisplayName when the card has no name.
	if len(ct.Emails) > 0 {
		ct.Email = ct.Emails[0].Value
	}
	if ct.Name == "" {
		ct.Name = strings.TrimSpace(strings.Join([]string{ct.FirstName, ct.LastName}, " "))
	}
	if ct.Name == "" {
		ct.Name = ct.Email
	}
	return ct
}

// Encode serializes a Contact, preserving every non-base line from the
// previously stored card so CardDAV-only fields (ADR, NOTE, BDAY, ...) survive
// edits made in the web UI.
func Encode(ct contacts.Contact, previous string) string {
	var extras []string
	for _, line := range unfold(previous) {
		hdr, _ := splitLine(line)
		name := hdr
		if i := strings.IndexByte(hdr, ';'); i >= 0 {
			name = hdr[:i]
		}
		if !baseFields[strings.ToUpper(name)] {
			extras = append(extras, line)
		}
	}

	lines := []string{"BEGIN:VCARD", "VERSION:3.0"}
	if fn := ct.DisplayName(); fn != "" {
		lines = append(lines, "FN:"+escapeValue(fn))
	}
	if ct.FirstName != "" || ct.LastName != "" {
		lines = append(lines, "N:"+escapeValue(ct.LastName)+";"+escapeValue(ct.FirstName)+";;;")
	} else if ct.Name != "" {
		lines = append(lines, "N:"+escapeValue(ct.Name)+";;;;")
	}
	if uid := uidFor(ct, previous); uid != "" {
		lines = append(lines, "UID:"+escapeValue(uid))
	}
	if ct.Company != "" {
		lines = append(lines, "ORG:"+escapeValue(ct.Company))
	}
	if ct.Title != "" {
		lines = append(lines, "TITLE:"+escapeValue(ct.Title))
	}
	for _, f := range ct.Phones {
		if line := fieldLine("TEL", f); line != "" {
			lines = append(lines, line)
		}
	}
	for _, f := range ct.Emails {
		if line := fieldLine("EMAIL", f); line != "" {
			lines = append(lines, line)
		}
	}
	lines = append(lines, extras...)
	lines = append(lines, "END:VCARD")

	var out []string
	for _, l := range lines {
		out = append(out, foldLine(l))
	}
	return strings.Join(out, "\n")
}

func unfold(v string) []string {
	var lines []string
	var buf string
	for _, raw := range strings.Split(v, "\n") {
		line := strings.TrimSuffix(raw, "\r")
		if len(line) > 0 && (line[0] == ' ' || line[0] == '\t') && buf != "" {
			if len(line) > 1 {
				buf += line[1:]
			}
			continue
		}
		if buf != "" {
			lines = append(lines, buf)
		}
		buf = line
	}
	if buf != "" {
		lines = append(lines, buf)
	}
	return lines
}

func splitLine(line string) (header, value string) {
	if i := strings.IndexByte(line, ':'); i >= 0 {
		return line[:i], line[i+1:]
	}
	return line, ""
}

func escapeValue(v string) string {
	v = strings.ReplaceAll(v, `\`, `\\`)
	v = strings.ReplaceAll(v, "\n", `\n`)
	v = strings.ReplaceAll(v, ",", `\,`)
	v = strings.ReplaceAll(v, ";", `\;`)
	return v
}

func unescapeValue(v string) string {
	v = strings.ReplaceAll(v, `\n`, "\n")
	v = strings.ReplaceAll(v, `\N`, "\n")
	v = strings.ReplaceAll(v, `\,`, ",")
	v = strings.ReplaceAll(v, `\;`, ";")
	v = strings.ReplaceAll(v, `\\`, `\`)
	return v
}

// splitEscaped splits on sep, ignoring separators escaped with a backslash
// (RFC 2426 uses \n, \, and \; inside escaped values).
func splitEscaped(s string, sep byte) []string {
	var parts []string
	var cur strings.Builder
	escaped := false
	for i := 0; i < len(s); i++ {
		c := s[i]
		switch {
		case escaped:
			escaped = false
		case c == '\\':
			escaped = true
		case c == sep:
			parts = append(parts, cur.String())
			cur.Reset()
			continue
		}
		cur.WriteByte(c)
	}
	parts = append(parts, cur.String())
	return parts
}

// foldLine folds a line at 75 octets (RFC 6868 / RFC 2426), staying on
// UTF-8 rune boundaries.
func foldLine(s string) string {
	if len(s) <= 75 {
		return s
	}
	var out []string
	for len(s) > 75 {
		cut := 75
		for cut > 0 && !utf8.RuneStart(s[cut]) {
			cut--
		}
		if cut == 0 {
			cut = 75
		}
		out = append(out, s[:cut])
		s = s[cut:]
	}
	out = append(out, s)
	return strings.Join(out, "\n ")
}

func fieldFromLine(hdr, val string) contacts.Field {
	f := contacts.Field{Header: hdr, Value: strings.TrimSpace(unescapeValue(val))}
	if i := strings.IndexByte(hdr, ';'); i >= 0 {
		for _, param := range strings.Split(hdr[i+1:], ";") {
			name, value, ok := strings.Cut(strings.TrimSpace(param), "=")
			if !ok {
				continue
			}
			if strings.EqualFold(name, "TYPE") {
				for _, t := range strings.Split(value, ",") {
					if t = strings.TrimSpace(t); t != "" {
						f.Type = append(f.Type, strings.ToUpper(t))
					}
				}
			}
		}
	}
	return f
}

func fieldLine(kind string, f contacts.Field) string {
	if strings.TrimSpace(f.Value) == "" {
		return ""
	}
	types := make([]string, 0, len(f.Type)+1)
	seen := make(map[string]bool)
	add := func(t string) {
		t = strings.ToUpper(strings.TrimSpace(t))
		if t == "" || seen[t] {
			return
		}
		seen[t] = true
		types = append(types, t)
	}
	if kind == "EMAIL" {
		add("INTERNET")
	}
	for _, t := range f.Type {
		if strings.EqualFold(t, "INTERNET") {
			continue
		}
		add(t)
	}
	if kind == "TEL" && !seen["VOICE"] && !seen["CELL"] && !seen["FAX"] && !seen["PAGER"] && !seen["TEXT"] {
		add("VOICE")
	}
	if len(types) == 0 {
		return kind + ":" + escapeValue(f.Value)
	}
	return kind + ";TYPE=" + strings.Join(types, ",") + ":" + escapeValue(f.Value)
}

func uidFor(ct contacts.Contact, prev string) string {
	if uid := strings.TrimSpace(ct.UID); uid != "" {
		return uid
	}
	for _, line := range unfold(prev) {
		hdr, val := splitLine(line)
		name := hdr
		if i := strings.IndexByte(hdr, ';'); i >= 0 {
			name = hdr[:i]
		}
		if strings.EqualFold(name, "UID") {
			if uid := strings.TrimSpace(unescapeValue(val)); uid != "" {
				return uid
			}
		}
	}
	if ct.ID != uuid.Nil {
		return ct.ID.String()
	}
	return ""
}
